---
# Grant anyuid SCC to postgres-pod ServiceAccount
# The namespace will be set by the overlay's kustomization.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-pod-anyuid
  labels:
    app: postgres-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: postgres-pod
