---
# RoleBinding for dba-prod to manage Applications in dba-prod namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dba-prod-application-manager
  namespace: dba-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-application-manager
subjects:
  - kind: User
    name: dba-prod
    apiGroup: rbac.authorization.k8s.io
  # Master DBA also gets access
  - kind: User
    name: dba
    apiGroup: rbac.authorization.k8s.io
