apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dba-prod

resources:
  - namespace-rbac.yaml
  - ../../base
  - ha-cluster.yaml
  - application-manager-binding.yaml
  - ../../../../../frontend/base
  - frontend.yaml

patches:
  - path: frontend-patch.yaml

images:
  - name: frontend:latest
    newName: image-registry.openshift-image-registry.svc:5000/dba-prod/frontend
    newTag: latest

commonAnnotations:
  environment: prod
