---
# RoleBinding for dba-dev to manage Applications in dba-dev namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dba-dev-application-manager
  namespace: dba-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-application-manager
subjects:
  - kind: User
    name: dba-dev
    apiGroup: rbac.authorization.k8s.io
  # Master DBA also gets access
  - kind: User
    name: dba
    apiGroup: rbac.authorization.k8s.io
