apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dba-dev

resources:
  - namespace-rbac.yaml
  - ../../base
  - simple-cluster.yaml
  - application-manager-binding.yaml
  - ../../../../../frontend/base
  - frontend.yaml          # ConfigMap with env-specific DB config

patches:
  - path: frontend-patch.yaml

images:
  - name: frontend:latest
    newName: image-registry.openshift-image-registry.svc:5000/dba-dev/frontend
    newTag: latest

commonAnnotations:
  environment: dev
